---

- name: Creates backend directory
  file:
    path: ~/backend
    state: directory

- name: Copy the backend zip
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/backend/artifact.tar.gz"

- name: unpack backend zip
  become: yes
  shell: |
    cd backend
    tar -xzvf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start backend
  become: yes
  shell: |
    cd backend
    sudo npm install --quiet
    sudo pm2 stop default
    sudo pm2 start npm -- start

