---

- name: Creates backend directory
  file:
    path: ~/backend
    state: directory

- name: Copy the backend zip
  template:
    src: "backend/artifact.tar.gz"
    dest: "~/backend/artifact.tar.gz"

- name: unpack backend zip
  become: yes
  shell: |
    cd backend
    tar -xzvf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start backend
  become: yes
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start

