---

- name: Creates backend directory
  file:
    path: ~/project/backend
    state: directory

- name: Copy the backend zip
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/project/backend/artifact.tar.gz"

- name: unpack backend zip
  become: yes
  shell: |
    cd project
    cd backend
    ls
    tar -xzvf artifact.tar.gz
    ls
    rm -f artifact.tar.gz
    ls

- name: start backend
  become: yes
  shell: |
    cd project
    cd backend
    npm install
    ls
    # pm2 stop default
    pm2 start npm -- start

